### PR TITLE
Fix transip 

### PR DESCRIPTION
**Pull request by zjean**
- implemented #6 to clean up fqdn
- Set Correct TTL if it is too low, to prevent errors from the transip api.

### CODE REVIEW

**Comment by boukeversteegh** [comment]
This change is needed downstream for caddy-dns, to support transip in caddy. Would be great if this could get approved :-)

**Comment by tIsGoud** [comment]
The caddy-dns is also on my wish-list. It seems part of the work is already done by @zjean but that was 6 months ago.
Are there more dependencies that need to be solved?

**Comment by mholt** [comment]
If the maintainer remains absent, I can merge this if you can verify that this works correctly. (I don't use TransIP)

**Comment by zjean** [comment]
Hi @mholt, that would be great. I run this in production in my self built docker container for months, so yes it work.

**Comment by tIsGoud** [comment]
Thanks @mholt and @zjean for picking this up!

**Comment by mdbraber** [comment]
@mholt @tIsGoud @zjean sorry for being away; I currently don't have the time to focus on getting this merged but would be happy to transfer ownership to get this done. Thanks!

**Pull request merged**
